import type { Recipe } from "@/types/recipe";
import demoBlackBeanRiceSkillet from "@/assets/demo-black-bean-rice-skillet.jpg";
import demoCheddarBeanStuffedTortillas from "@/assets/demo-cheddar-bean-stuffed-tortillas.jpg";
import demoCheesyChickenQuesadillas from "@/assets/demo-cheesy-chicken-quesadillas.jpg";
import demoChickenBlackBeanTacos from "@/assets/demo-chicken-black-bean-tacos.jpg";
import demoChickenBurritoRiceBowls from "@/assets/demo-chicken-burrito-rice-bowls.jpg";
import demoCilantroLemonBlackBeanTacos from "@/assets/demo-cilantro-lemon-black-bean-tacos.jpg";
import demoLemonYogurtChickenTacos from "@/assets/demo-lemon-yogurt-chicken-tacos.jpg";
import demoTomatoGarlicChickenRice from "@/assets/demo-tomato-garlic-chicken-rice.jpg";

/**
 * Mock recipe data for demo mode.
 * Covers various pantry combinations for testing:
 * - Full matches (chicken+garlic+oil+rice, pasta+tomato+garlic, eggs+butter+flour)
 * - Partial matches with missing ingredients
 * - Partial matches with insufficient quantities
 * - Recipe with no image (for fallback testing)
 */
export const MOCK_RECIPES: Recipe[] = [
  {
    id: 101,
    title: "Garlic Butter Chicken with Rice",
    image: "https://img.spoonacular.com/recipes/716429-312x231.jpg",
    usedIngredientCount: 4,
    missedIngredientCount: 0,
    usedIngredients: [
      { id: 1, name: "chicken breast", amount: 2, unit: "pieces", original: "2 chicken breasts" },
      { id: 2, name: "garlic", amount: 4, unit: "cloves", original: "4 cloves garlic" },
      { id: 3, name: "olive oil", amount: 2, unit: "tbsp", original: "2 tablespoons olive oil" },
      { id: 4, name: "rice", amount: 1, unit: "cup", original: "1 cup rice" },
    ],
    missedIngredients: [],
    servings: 4,
    readyInMinutes: 35,
    instructions:
      "<ol><li>Season chicken breasts with salt and pepper.</li><li>Heat olive oil in a large skillet over medium-high heat.</li><li>Cook chicken 6-7 minutes per side until golden and cooked through.</li><li>Mince garlic and sauté in the same pan for 1 minute.</li><li>Add a tablespoon of butter and pour over chicken.</li><li>Serve over cooked rice.</li></ol>",
    sourceUrl: "https://example.com/garlic-butter-chicken",
    extendedIngredients: [
      { id: 1, name: "chicken breast", amount: 200, unit: "g", original: "200g chicken breast" },
      { id: 2, name: "garlic", amount: 4, unit: "cloves", original: "4 cloves garlic" },
      { id: 3, name: "olive oil", amount: 2, unit: "tbsp", original: "2 tablespoons olive oil" },
      { id: 4, name: "rice", amount: 1, unit: "cup", original: "1 cup rice" },
      { id: 5, name: "butter", amount: 1, unit: "tbsp", original: "1 tablespoon butter" },
      { id: 6, name: "salt", amount: 1, unit: "tsp", original: "1 tsp salt" },
    ],
  },
  {
    id: 102,
    title: "One-Pot Chicken & Rice",
    image: "https://img.spoonacular.com/recipes/715594-312x231.jpg",
    usedIngredientCount: 4,
    missedIngredientCount: 0,
    usedIngredients: [
      { id: 1, name: "chicken breast", amount: 1, unit: "lb", original: "1 lb chicken breast" },
      { id: 2, name: "garlic", amount: 3, unit: "cloves", original: "3 cloves garlic" },
      { id: 3, name: "olive oil", amount: 1, unit: "tbsp", original: "1 tablespoon olive oil" },
      { id: 4, name: "rice", amount: 1.5, unit: "cups", original: "1.5 cups rice" },
    ],
    missedIngredients: [],
    servings: 4,
    readyInMinutes: 40,
    instructions:
      "<ol><li>Dice chicken breast into 1-inch cubes.</li><li>Heat olive oil in a pot over medium heat.</li><li>Add chicken and cook until browned, about 5 minutes.</li><li>Add minced garlic and sauté for 1 minute.</li><li>Stir in rice and 3 cups of water or broth.</li><li>Bring to a boil, reduce heat to low, cover and cook 20 minutes.</li><li>Fluff with a fork and serve.</li></ol>",
    sourceUrl: "https://example.com/one-pot-chicken-rice",
    extendedIngredients: [
      { id: 1, name: "chicken breast", amount: 450, unit: "g", original: "1 lb chicken breast" },
      { id: 2, name: "garlic", amount: 3, unit: "cloves", original: "3 cloves garlic" },
      { id: 3, name: "olive oil", amount: 1, unit: "tbsp", original: "1 tablespoon olive oil" },
      { id: 4, name: "rice", amount: 1.5, unit: "cups", original: "1.5 cups rice" },
      { id: 5, name: "chicken broth", amount: 3, unit: "cups", original: "3 cups chicken broth" },
    ],
  },
  {
    id: 103,
    title: "Lemon Herb Chicken Thighs",
    image: "https://img.spoonacular.com/recipes/782585-312x231.jpg",
    usedIngredientCount: 3,
    missedIngredientCount: 2,
    usedIngredients: [
      { id: 1, name: "chicken breast", amount: 1, unit: "lb", original: "1 lb chicken" },
      { id: 2, name: "garlic", amount: 2, unit: "cloves", original: "2 cloves garlic" },
      { id: 3, name: "olive oil", amount: 2, unit: "tbsp", original: "2 tablespoons olive oil" },
    ],
    missedIngredients: [
      { id: 7, name: "lemon", amount: 1, unit: "", original: "1 lemon, juiced" },
      { id: 8, name: "fresh thyme", amount: 2, unit: "sprigs", original: "2 sprigs fresh thyme" },
    ],
    servings: 4,
    readyInMinutes: 45,
    instructions:
      "<ol><li>Preheat oven to 400°F.</li><li>Mix olive oil, minced garlic, lemon juice, and thyme.</li><li>Coat chicken in the marinade.</li><li>Place in a baking dish and roast for 35-40 minutes.</li><li>Serve hot with your favourite sides.</li></ol>",
    sourceUrl: "https://example.com/lemon-herb-chicken",
    extendedIngredients: [
      { id: 1, name: "chicken breast", amount: 450, unit: "g", original: "1 lb chicken" },
      { id: 2, name: "garlic", amount: 2, unit: "cloves", original: "2 cloves garlic" },
      { id: 3, name: "olive oil", amount: 2, unit: "tbsp", original: "2 tablespoons olive oil" },
      { id: 7, name: "lemon", amount: 1, unit: "", original: "1 lemon, juiced" },
      { id: 8, name: "fresh thyme", amount: 2, unit: "sprigs", original: "2 sprigs fresh thyme" },
    ],
  },
  {
    id: 104,
    title: "Chicken Stir Fry with Vegetables",
    image: "https://img.spoonacular.com/recipes/663559-312x231.jpg",
    usedIngredientCount: 3,
    missedIngredientCount: 3,
    usedIngredients: [
      { id: 1, name: "chicken breast", amount: 300, unit: "g", original: "300g chicken breast" },
      { id: 2, name: "garlic", amount: 3, unit: "cloves", original: "3 cloves garlic" },
      { id: 3, name: "olive oil", amount: 1, unit: "tbsp", original: "1 tablespoon olive oil" },
    ],
    missedIngredients: [
      { id: 9, name: "soy sauce", amount: 2, unit: "tbsp", original: "2 tablespoons soy sauce" },
      { id: 10, name: "bell pepper", amount: 1, unit: "", original: "1 bell pepper, sliced" },
      { id: 11, name: "broccoli", amount: 1, unit: "cup", original: "1 cup broccoli florets" },
    ],
    servings: 3,
    readyInMinutes: 25,
    instructions:
      "<ol><li>Slice chicken breast into thin strips.</li><li>Heat olive oil in a wok over high heat.</li><li>Stir-fry chicken for 4-5 minutes.</li><li>Add garlic, bell pepper, and broccoli. Cook 3-4 minutes.</li><li>Pour in soy sauce and toss to coat.</li><li>Serve immediately over rice.</li></ol>",
    sourceUrl: "https://example.com/chicken-stir-fry",
    extendedIngredients: [
      { id: 1, name: "chicken breast", amount: 300, unit: "g", original: "300g chicken breast" },
      { id: 2, name: "garlic", amount: 3, unit: "cloves", original: "3 cloves garlic" },
      { id: 3, name: "olive oil", amount: 1, unit: "tbsp", original: "1 tablespoon olive oil" },
      { id: 9, name: "soy sauce", amount: 2, unit: "tbsp", original: "2 tablespoons soy sauce" },
      { id: 10, name: "bell pepper", amount: 1, unit: "", original: "1 bell pepper, sliced" },
      { id: 11, name: "broccoli", amount: 1, unit: "cup", original: "1 cup broccoli florets" },
    ],
  },
  {
    id: 105,
    title: "Classic Chicken Parmesan Pasta",
    image: "https://img.spoonacular.com/recipes/654959-312x231.jpg",
    usedIngredientCount: 5,
    missedIngredientCount: 0,
    usedIngredients: [
      { id: 1, name: "chicken breast", amount: 500, unit: "g", original: "500g chicken breast" },
      { id: 2, name: "garlic", amount: 3, unit: "cloves", original: "3 cloves garlic" },
      { id: 3, name: "olive oil", amount: 2, unit: "tbsp", original: "2 tablespoons olive oil" },
      { id: 12, name: "spaghetti", amount: 400, unit: "g", original: "400g spaghetti" },
      { id: 13, name: "parmesan", amount: 80, unit: "g", original: "80g parmesan" },
    ],
    missedIngredients: [],
    servings: 4,
    readyInMinutes: 30,
    instructions:
      "<ol><li>Cook spaghetti according to package directions.</li><li>Season chicken with salt and pepper, coat lightly in flour.</li><li>Heat olive oil and cook chicken 5-6 min per side until golden.</li><li>In same pan, sauté garlic for 1 minute.</li><li>Toss pasta with garlic oil, top with sliced chicken and grated parmesan.</li></ol>",
    sourceUrl: "https://example.com/chicken-parm-pasta",
    extendedIngredients: [
      { id: 1, name: "chicken breast", amount: 500, unit: "g", original: "500g chicken breast" },
      { id: 2, name: "garlic", amount: 3, unit: "cloves", original: "3 cloves garlic" },
      { id: 3, name: "olive oil", amount: 2, unit: "tbsp", original: "2 tablespoons olive oil" },
      { id: 12, name: "spaghetti", amount: 400, unit: "g", original: "400g spaghetti" },
      { id: 13, name: "parmesan", amount: 80, unit: "g", original: "80g parmesan" },
    ],
  },
  {
    id: 106,
    title: "Tomato Garlic Spaghetti",
    image: "https://img.spoonacular.com/recipes/716195-312x231.jpg",
    usedIngredientCount: 4,
    missedIngredientCount: 0,
    usedIngredients: [
      { id: 2, name: "garlic", amount: 4, unit: "cloves", original: "4 cloves garlic" },
      { id: 3, name: "olive oil", amount: 3, unit: "tbsp", original: "3 tablespoons olive oil" },
      { id: 12, name: "spaghetti", amount: 300, unit: "g", original: "300g spaghetti" },
      { id: 14, name: "tomato", amount: 400, unit: "g", original: "400g tomatoes" },
    ],
    missedIngredients: [],
    servings: 3,
    readyInMinutes: 20,
    instructions:
      "<ol><li>Cook spaghetti al dente.</li><li>Dice tomatoes. Heat olive oil, sauté garlic 1 min.</li><li>Add tomatoes, cook 8-10 min until saucy.</li><li>Toss pasta in the sauce, season with salt and pepper.</li></ol>",
    sourceUrl: "https://example.com/tomato-garlic-spaghetti",
    extendedIngredients: [
      { id: 2, name: "garlic", amount: 4, unit: "cloves", original: "4 cloves garlic" },
      { id: 3, name: "olive oil", amount: 3, unit: "tbsp", original: "3 tablespoons olive oil" },
      { id: 12, name: "spaghetti", amount: 300, unit: "g", original: "300g spaghetti" },
      { id: 14, name: "tomato", amount: 400, unit: "g", original: "400g tomatoes" },
    ],
  },
  // --- NEW: Egg-based recipe (full match with eggs, butter, flour, milk) ---
  {
    id: 107,
    title: "Fluffy Buttermilk Pancakes",
    image: "https://img.spoonacular.com/recipes/639468-312x231.jpg",
    usedIngredientCount: 4,
    missedIngredientCount: 0,
    usedIngredients: [
      { id: 20, name: "egg", amount: 2, unit: "", original: "2 eggs" },
      { id: 21, name: "all-purpose flour", amount: 200, unit: "g", original: "200g flour" },
      { id: 22, name: "whole milk", amount: 250, unit: "ml", original: "250ml milk" },
      { id: 23, name: "butter", amount: 30, unit: "g", original: "30g butter" },
    ],
    missedIngredients: [],
    servings: 4,
    readyInMinutes: 20,
    instructions:
      "<ol><li>Whisk flour, a pinch of salt, and 1 tsp baking powder.</li><li>In another bowl, beat eggs, then add milk and melted butter.</li><li>Combine wet and dry ingredients until just mixed.</li><li>Heat a non-stick pan over medium heat, ladle batter to form pancakes.</li><li>Cook 2-3 minutes per side until golden brown.</li><li>Serve with maple syrup or fresh fruit.</li></ol>",
    sourceUrl: "https://example.com/buttermilk-pancakes",
    extendedIngredients: [
      { id: 20, name: "egg", amount: 2, unit: "", original: "2 eggs" },
      { id: 21, name: "all-purpose flour", amount: 200, unit: "g", original: "200g flour" },
      { id: 22, name: "whole milk", amount: 250, unit: "ml", original: "250ml milk" },
      { id: 23, name: "butter", amount: 30, unit: "g", original: "30g butter" },
      { id: 24, name: "baking powder", amount: 1, unit: "tsp", original: "1 tsp baking powder" },
    ],
  },
  // --- NEW: Salmon recipe (partial match — missing dill and lemon) ---
  {
    id: 108,
    title: "Honey Glazed Salmon",
    image: "https://img.spoonacular.com/recipes/644387-312x231.jpg",
    usedIngredientCount: 2,
    missedIngredientCount: 2,
    usedIngredients: [
      { id: 30, name: "salmon", amount: 400, unit: "g", original: "400g salmon fillet" },
      { id: 3, name: "olive oil", amount: 1, unit: "tbsp", original: "1 tablespoon olive oil" },
    ],
    missedIngredients: [
      { id: 31, name: "honey", amount: 3, unit: "tbsp", original: "3 tablespoons honey" },
      { id: 32, name: "lemon", amount: 1, unit: "", original: "1 lemon, juiced" },
    ],
    servings: 2,
    readyInMinutes: 25,
    instructions:
      "<ol><li>Preheat oven to 400°F (200°C).</li><li>Place salmon on a lined baking sheet, drizzle with olive oil.</li><li>Mix honey and lemon juice, brush generously over salmon.</li><li>Bake 12-15 minutes until salmon flakes easily.</li><li>Serve with steamed vegetables or rice.</li></ol>",
    sourceUrl: "https://example.com/honey-glazed-salmon",
    extendedIngredients: [
      { id: 30, name: "salmon", amount: 400, unit: "g", original: "400g salmon fillet" },
      { id: 3, name: "olive oil", amount: 1, unit: "tbsp", original: "1 tablespoon olive oil" },
      { id: 31, name: "honey", amount: 3, unit: "tbsp", original: "3 tablespoons honey" },
      { id: 32, name: "lemon", amount: 1, unit: "", original: "1 lemon, juiced" },
    ],
  },
  // --- NEW: Vegetarian recipe (full match with common pantry staples) ---
  {
    id: 109,
    title: "Creamy Garlic Mushroom Pasta",
    image: "https://img.spoonacular.com/recipes/660290-312x231.jpg",
    usedIngredientCount: 4,
    missedIngredientCount: 0,
    usedIngredients: [
      { id: 2, name: "garlic", amount: 4, unit: "cloves", original: "4 cloves garlic" },
      { id: 3, name: "olive oil", amount: 2, unit: "tbsp", original: "2 tablespoons olive oil" },
      { id: 40, name: "button mushrooms", amount: 250, unit: "g", original: "250g mushrooms" },
      { id: 41, name: "penne", amount: 300, unit: "g", original: "300g penne" },
    ],
    missedIngredients: [],
    servings: 3,
    readyInMinutes: 25,
    instructions:
      "<ol><li>Cook penne according to package directions.</li><li>Slice mushrooms. Heat olive oil, sauté mushrooms 5-6 minutes until golden.</li><li>Add minced garlic, cook 1 minute.</li><li>Pour in heavy cream and simmer 3 minutes.</li><li>Toss cooked pasta into the sauce. Season with salt and pepper.</li></ol>",
    sourceUrl: "https://example.com/creamy-garlic-mushroom-pasta",
    extendedIngredients: [
      { id: 2, name: "garlic", amount: 4, unit: "cloves", original: "4 cloves garlic" },
      { id: 3, name: "olive oil", amount: 2, unit: "tbsp", original: "2 tablespoons olive oil" },
      { id: 40, name: "button mushrooms", amount: 250, unit: "g", original: "250g mushrooms" },
      { id: 41, name: "penne", amount: 300, unit: "g", original: "300g penne" },
      { id: 42, name: "heavy cream", amount: 100, unit: "ml", original: "100ml heavy cream" },
    ],
  },
  // --- NEW: Recipe with NO image (for fallback/placeholder testing) ---
  {
    id: 110,
    title: "Simple Egg Fried Rice",
    image: "",
    usedIngredientCount: 3,
    missedIngredientCount: 1,
    usedIngredients: [
      { id: 20, name: "egg", amount: 3, unit: "", original: "3 eggs" },
      { id: 4, name: "rice", amount: 2, unit: "cups", original: "2 cups cooked rice" },
      { id: 3, name: "olive oil", amount: 1, unit: "tbsp", original: "1 tablespoon oil" },
    ],
    missedIngredients: [
      { id: 9, name: "soy sauce", amount: 2, unit: "tbsp", original: "2 tablespoons soy sauce" },
    ],
    servings: 2,
    readyInMinutes: 15,
    instructions:
      "<ol><li>Heat oil in a wok over high heat.</li><li>Scramble eggs, break into small pieces.</li><li>Add cooked rice, stir-fry 3-4 minutes.</li><li>Drizzle soy sauce and toss to combine.</li><li>Serve immediately.</li></ol>",
    sourceUrl: "https://example.com/egg-fried-rice",
    extendedIngredients: [
      { id: 20, name: "egg", amount: 3, unit: "", original: "3 eggs" },
      { id: 4, name: "rice", amount: 2, unit: "cups", original: "2 cups cooked rice" },
      { id: 3, name: "olive oil", amount: 1, unit: "tbsp", original: "1 tablespoon oil" },
      { id: 9, name: "soy sauce", amount: 2, unit: "tbsp", original: "2 tablespoons soy sauce" },
    ],
  },
  // --- NEW: Beef recipe (partial — needs red wine and rosemary) ---
  {
    id: 111,
    title: "Pan-Seared Steak with Garlic Butter",
    image: "https://img.spoonacular.com/recipes/633876-312x231.jpg",
    usedIngredientCount: 3,
    missedIngredientCount: 1,
    usedIngredients: [
      { id: 50, name: "steak", amount: 400, unit: "g", original: "400g ribeye steak" },
      { id: 2, name: "garlic", amount: 3, unit: "cloves", original: "3 cloves garlic" },
      { id: 23, name: "butter", amount: 30, unit: "g", original: "30g butter" },
    ],
    missedIngredients: [
      { id: 51, name: "rosemary", amount: 2, unit: "sprigs", original: "2 sprigs fresh rosemary" },
    ],
    servings: 2,
    readyInMinutes: 20,
    instructions:
      "<ol><li>Bring steak to room temperature. Season generously with salt and pepper.</li><li>Heat a cast-iron skillet over high heat until smoking.</li><li>Sear steak 3-4 minutes per side for medium-rare.</li><li>Add butter, garlic, and rosemary. Baste steak for 1 minute.</li><li>Rest 5 minutes before slicing.</li></ol>",
    sourceUrl: "https://example.com/garlic-butter-steak",
    extendedIngredients: [
      { id: 50, name: "steak", amount: 400, unit: "g", original: "400g ribeye steak" },
      { id: 2, name: "garlic", amount: 3, unit: "cloves", original: "3 cloves garlic" },
      { id: 23, name: "butter", amount: 30, unit: "g", original: "30g butter" },
      { id: 51, name: "rosemary", amount: 2, unit: "sprigs", original: "2 sprigs fresh rosemary" },
    ],
  },
  {
    id: 112,
    title: "Chicken Black Bean Tacos",
    image: demoChickenBlackBeanTacos,
    usedIngredientCount: 10,
    missedIngredientCount: 0,
    usedIngredients: [
      { id: 60, name: "chicken breast", amount: 2, unit: "piece", original: "2 chicken breasts" },
      { id: 61, name: "tortilla", amount: 6, unit: "piece", original: "6 tortillas" },
      { id: 62, name: "black beans", amount: 1, unit: "can", original: "1 can black beans" },
      { id: 63, name: "onion", amount: 1, unit: "piece", original: "1 onion" },
      { id: 64, name: "garlic", amount: 3, unit: "clove", original: "3 cloves garlic" },
      { id: 65, name: "tomato", amount: 2, unit: "piece", original: "2 tomatoes" },
      { id: 66, name: "cheddar cheese", amount: 80, unit: "g", original: "80g cheddar cheese" },
      { id: 67, name: "greek yogurt", amount: 120, unit: "g", original: "120g Greek yogurt" },
      { id: 68, name: "lemon", amount: 1, unit: "piece", original: "1 lemon" },
      { id: 69, name: "cilantro", amount: 1, unit: "bunch", original: "1 bunch cilantro" },
    ],
    missedIngredients: [],
    servings: 3,
    readyInMinutes: 30,
    instructions:
      "<ol><li>Dice chicken and cook with onion and garlic until browned.</li><li>Warm black beans with chopped tomato.</li><li>Stir lemon juice into Greek yogurt for a quick crema.</li><li>Fill tortillas with chicken, beans, cheddar, cilantro, and crema.</li></ol>",
    sourceUrl: "https://example.com/chicken-black-bean-tacos",
    extendedIngredients: [
      { id: 60, name: "chicken breast", amount: 2, unit: "piece", original: "2 chicken breasts" },
      { id: 61, name: "tortilla", amount: 6, unit: "piece", original: "6 tortillas" },
      { id: 62, name: "black beans", amount: 1, unit: "can", original: "1 can black beans" },
      { id: 63, name: "onion", amount: 1, unit: "piece", original: "1 onion" },
      { id: 64, name: "garlic", amount: 3, unit: "clove", original: "3 cloves garlic" },
      { id: 65, name: "tomato", amount: 2, unit: "piece", original: "2 tomatoes" },
      { id: 66, name: "cheddar cheese", amount: 80, unit: "g", original: "80g cheddar cheese" },
      { id: 67, name: "greek yogurt", amount: 120, unit: "g", original: "120g Greek yogurt" },
      { id: 68, name: "lemon", amount: 1, unit: "piece", original: "1 lemon" },
      { id: 69, name: "cilantro", amount: 1, unit: "bunch", original: "1 bunch cilantro" },
    ],
  },
  {
    id: 113,
    title: "Cheesy Chicken Quesadillas",
    image: demoCheesyChickenQuesadillas,
    usedIngredientCount: 6,
    missedIngredientCount: 0,
    usedIngredients: [
      { id: 60, name: "chicken breast", amount: 1, unit: "piece", original: "1 chicken breast" },
      { id: 61, name: "tortilla", amount: 4, unit: "piece", original: "4 tortillas" },
      { id: 66, name: "cheddar cheese", amount: 80, unit: "g", original: "80g cheddar cheese" },
      { id: 63, name: "onion", amount: 0.5, unit: "piece", original: "1/2 onion" },
      { id: 64, name: "garlic", amount: 1, unit: "clove", original: "1 clove garlic" },
      { id: 23, name: "butter", amount: 20, unit: "g", original: "20g butter" },
    ],
    missedIngredients: [],
    servings: 2,
    readyInMinutes: 18,
    instructions:
      "<ol><li>Shred cooked chicken and mix with sautéed onion and garlic.</li><li>Layer chicken and cheddar between tortillas.</li><li>Cook in butter until crisp and golden on both sides.</li><li>Slice into wedges and serve with Greek yogurt.</li></ol>",
    sourceUrl: "https://example.com/cheesy-chicken-quesadillas",
    extendedIngredients: [
      { id: 60, name: "chicken breast", amount: 1, unit: "piece", original: "1 chicken breast" },
      { id: 61, name: "tortilla", amount: 4, unit: "piece", original: "4 tortillas" },
      { id: 66, name: "cheddar cheese", amount: 80, unit: "g", original: "80g cheddar cheese" },
      { id: 63, name: "onion", amount: 0.5, unit: "piece", original: "1/2 onion" },
      { id: 64, name: "garlic", amount: 1, unit: "clove", original: "1 clove garlic" },
      { id: 23, name: "butter", amount: 20, unit: "g", original: "20g butter" },
    ],
  },
  {
    id: 114,
    title: "Chicken Burrito Rice Bowls",
    image: demoChickenBurritoRiceBowls,
    usedIngredientCount: 8,
    missedIngredientCount: 0,
    usedIngredients: [
      { id: 60, name: "chicken breast", amount: 2, unit: "piece", original: "2 chicken breasts" },
      { id: 4, name: "rice", amount: 1, unit: "cup", original: "1 cup rice" },
      { id: 62, name: "black beans", amount: 1, unit: "can", original: "1 can black beans" },
      { id: 65, name: "tomato", amount: 2, unit: "piece", original: "2 tomatoes" },
      { id: 63, name: "onion", amount: 1, unit: "piece", original: "1 onion" },
      { id: 64, name: "garlic", amount: 2, unit: "clove", original: "2 cloves garlic" },
      { id: 68, name: "lemon", amount: 1, unit: "piece", original: "1 lemon" },
      { id: 69, name: "cilantro", amount: 1, unit: "bunch", original: "1 bunch cilantro" },
    ],
    missedIngredients: [],
    servings: 3,
    readyInMinutes: 35,
    instructions:
      "<ol><li>Cook rice until fluffy.</li><li>Sauté onion and garlic, then cook diced chicken until done.</li><li>Warm black beans and chop tomatoes.</li><li>Build bowls with rice, chicken, beans, tomato, cilantro, and lemon juice.</li></ol>",
    sourceUrl: "https://example.com/chicken-burrito-rice-bowls",
    extendedIngredients: [
      { id: 60, name: "chicken breast", amount: 2, unit: "piece", original: "2 chicken breasts" },
      { id: 4, name: "rice", amount: 1, unit: "cup", original: "1 cup rice" },
      { id: 62, name: "black beans", amount: 1, unit: "can", original: "1 can black beans" },
      { id: 65, name: "tomato", amount: 2, unit: "piece", original: "2 tomatoes" },
      { id: 63, name: "onion", amount: 1, unit: "piece", original: "1 onion" },
      { id: 64, name: "garlic", amount: 2, unit: "clove", original: "2 cloves garlic" },
      { id: 68, name: "lemon", amount: 1, unit: "piece", original: "1 lemon" },
      { id: 69, name: "cilantro", amount: 1, unit: "bunch", original: "1 bunch cilantro" },
    ],
  },
  {
    id: 115,
    title: "Black Bean & Rice Skillet",
    image: demoBlackBeanRiceSkillet,
    usedIngredientCount: 7,
    missedIngredientCount: 0,
    usedIngredients: [
      { id: 4, name: "rice", amount: 1, unit: "cup", original: "1 cup rice" },
      { id: 62, name: "black beans", amount: 1, unit: "can", original: "1 can black beans" },
      { id: 63, name: "onion", amount: 1, unit: "piece", original: "1 onion" },
      { id: 64, name: "garlic", amount: 2, unit: "clove", original: "2 cloves garlic" },
      { id: 65, name: "tomato", amount: 2, unit: "piece", original: "2 tomatoes" },
      { id: 66, name: "cheddar cheese", amount: 100, unit: "g", original: "100g cheddar cheese" },
      { id: 69, name: "cilantro", amount: 0.5, unit: "bunch", original: "1/2 bunch cilantro" },
    ],
    missedIngredients: [],
    servings: 3,
    readyInMinutes: 25,
    instructions:
      "<ol><li>Sauté onion and garlic until soft.</li><li>Add chopped tomatoes, black beans, and cooked rice.</li><li>Simmer until thick and hot.</li><li>Top with cheddar and cilantro before serving.</li></ol>",
    sourceUrl: "https://example.com/black-bean-rice-skillet",
    extendedIngredients: [
      { id: 4, name: "rice", amount: 1, unit: "cup", original: "1 cup rice" },
      { id: 62, name: "black beans", amount: 1, unit: "can", original: "1 can black beans" },
      { id: 63, name: "onion", amount: 1, unit: "piece", original: "1 onion" },
      { id: 64, name: "garlic", amount: 2, unit: "clove", original: "2 cloves garlic" },
      { id: 65, name: "tomato", amount: 2, unit: "piece", original: "2 tomatoes" },
      { id: 66, name: "cheddar cheese", amount: 100, unit: "g", original: "100g cheddar cheese" },
      { id: 69, name: "cilantro", amount: 0.5, unit: "bunch", original: "1/2 bunch cilantro" },
    ],
  },
  {
    id: 116,
    title: "Lemon Yogurt Chicken Tacos",
    image: demoLemonYogurtChickenTacos,
    usedIngredientCount: 7,
    missedIngredientCount: 1,
    usedIngredients: [
      { id: 60, name: "chicken breast", amount: 2, unit: "piece", original: "2 chicken breasts" },
      { id: 61, name: "tortilla", amount: 6, unit: "piece", original: "6 tortillas" },
      { id: 67, name: "greek yogurt", amount: 150, unit: "g", original: "150g Greek yogurt" },
      { id: 68, name: "lemon", amount: 1, unit: "piece", original: "1 lemon" },
      { id: 64, name: "garlic", amount: 2, unit: "clove", original: "2 cloves garlic" },
      { id: 65, name: "tomato", amount: 1, unit: "piece", original: "1 tomato" },
      { id: 69, name: "cilantro", amount: 1, unit: "bunch", original: "1 bunch cilantro" },
    ],
    missedIngredients: [
      { id: 70, name: "cumin", amount: 1, unit: "tsp", original: "1 tsp cumin" },
    ],
    servings: 3,
    readyInMinutes: 28,
    instructions:
      "<ol><li>Marinate chicken with Greek yogurt, lemon juice, garlic, and cumin.</li><li>Cook chicken in a skillet until browned and cooked through.</li><li>Warm tortillas and fill with chicken, tomato, and cilantro.</li></ol>",
    sourceUrl: "https://example.com/lemon-yogurt-chicken-tacos",
    extendedIngredients: [
      { id: 60, name: "chicken breast", amount: 2, unit: "piece", original: "2 chicken breasts" },
      { id: 61, name: "tortilla", amount: 6, unit: "piece", original: "6 tortillas" },
      { id: 67, name: "greek yogurt", amount: 150, unit: "g", original: "150g Greek yogurt" },
      { id: 68, name: "lemon", amount: 1, unit: "piece", original: "1 lemon" },
      { id: 64, name: "garlic", amount: 2, unit: "clove", original: "2 cloves garlic" },
      { id: 65, name: "tomato", amount: 1, unit: "piece", original: "1 tomato" },
      { id: 69, name: "cilantro", amount: 1, unit: "bunch", original: "1 bunch cilantro" },
      { id: 70, name: "cumin", amount: 1, unit: "tsp", original: "1 tsp cumin" },
    ],
  },
  {
    id: 117,
    title: "Cheddar Bean Stuffed Tortillas",
    image: demoCheddarBeanStuffedTortillas,
    usedIngredientCount: 6,
    missedIngredientCount: 0,
    usedIngredients: [
      { id: 61, name: "tortilla", amount: 4, unit: "piece", original: "4 tortillas" },
      { id: 62, name: "black beans", amount: 1, unit: "can", original: "1 can black beans" },
      { id: 66, name: "cheddar cheese", amount: 100, unit: "g", original: "100g cheddar cheese" },
      { id: 65, name: "tomato", amount: 1, unit: "piece", original: "1 tomato" },
      { id: 63, name: "onion", amount: 0.5, unit: "piece", original: "1/2 onion" },
      { id: 23, name: "butter", amount: 20, unit: "g", original: "20g butter" },
    ],
    missedIngredients: [],
    servings: 2,
    readyInMinutes: 16,
    instructions:
      "<ol><li>Mash black beans lightly with chopped tomato and onion.</li><li>Spoon onto tortillas and add cheddar.</li><li>Fold and toast in butter until the cheese melts.</li><li>Serve hot with lemony yogurt if desired.</li></ol>",
    sourceUrl: "https://example.com/cheddar-bean-stuffed-tortillas",
    extendedIngredients: [
      { id: 61, name: "tortilla", amount: 4, unit: "piece", original: "4 tortillas" },
      { id: 62, name: "black beans", amount: 1, unit: "can", original: "1 can black beans" },
      { id: 66, name: "cheddar cheese", amount: 100, unit: "g", original: "100g cheddar cheese" },
      { id: 65, name: "tomato", amount: 1, unit: "piece", original: "1 tomato" },
      { id: 63, name: "onion", amount: 0.5, unit: "piece", original: "1/2 onion" },
      { id: 23, name: "butter", amount: 20, unit: "g", original: "20g butter" },
    ],
  },
  {
    id: 118,
    title: "Tomato Garlic Chicken Rice",
    image: demoTomatoGarlicChickenRice,
    usedIngredientCount: 6,
    missedIngredientCount: 0,
    usedIngredients: [
      { id: 60, name: "chicken breast", amount: 2, unit: "piece", original: "2 chicken breasts" },
      { id: 4, name: "rice", amount: 1, unit: "cup", original: "1 cup rice" },
      { id: 65, name: "tomato", amount: 2, unit: "piece", original: "2 tomatoes" },
      { id: 64, name: "garlic", amount: 3, unit: "clove", original: "3 cloves garlic" },
      { id: 63, name: "onion", amount: 1, unit: "piece", original: "1 onion" },
      { id: 23, name: "butter", amount: 30, unit: "g", original: "30g butter" },
    ],
    missedIngredients: [],
    servings: 3,
    readyInMinutes: 32,
    instructions:
      "<ol><li>Cook rice and set aside.</li><li>Brown chicken in butter, then add onion and garlic.</li><li>Add chopped tomatoes and simmer until saucy.</li><li>Serve chicken and tomato sauce over rice.</li></ol>",
    sourceUrl: "https://example.com/tomato-garlic-chicken-rice",
    extendedIngredients: [
      { id: 60, name: "chicken breast", amount: 2, unit: "piece", original: "2 chicken breasts" },
      { id: 4, name: "rice", amount: 1, unit: "cup", original: "1 cup rice" },
      { id: 65, name: "tomato", amount: 2, unit: "piece", original: "2 tomatoes" },
      { id: 64, name: "garlic", amount: 3, unit: "clove", original: "3 cloves garlic" },
      { id: 63, name: "onion", amount: 1, unit: "piece", original: "1 onion" },
      { id: 23, name: "butter", amount: 30, unit: "g", original: "30g butter" },
    ],
  },
  {
    id: 119,
    title: "Cilantro Lemon Black Bean Tacos",
    image: demoCilantroLemonBlackBeanTacos,
    usedIngredientCount: 7,
    missedIngredientCount: 0,
    usedIngredients: [
      { id: 61, name: "tortilla", amount: 6, unit: "piece", original: "6 tortillas" },
      { id: 62, name: "black beans", amount: 1, unit: "can", original: "1 can black beans" },
      { id: 65, name: "tomato", amount: 2, unit: "piece", original: "2 tomatoes" },
      { id: 63, name: "onion", amount: 1, unit: "piece", original: "1 onion" },
      { id: 69, name: "cilantro", amount: 1, unit: "bunch", original: "1 bunch cilantro" },
      { id: 68, name: "lemon", amount: 1, unit: "piece", original: "1 lemon" },
      { id: 67, name: "greek yogurt", amount: 100, unit: "g", original: "100g Greek yogurt" },
    ],
    missedIngredients: [],
    servings: 3,
    readyInMinutes: 20,
    instructions:
      "<ol><li>Warm black beans with onion and chopped tomato.</li><li>Mix Greek yogurt with lemon juice and chopped cilantro.</li><li>Warm tortillas and fill with beans.</li><li>Top with cilantro yogurt and extra tomato.</li></ol>",
    sourceUrl: "https://example.com/cilantro-lemon-black-bean-tacos",
    extendedIngredients: [
      { id: 61, name: "tortilla", amount: 6, unit: "piece", original: "6 tortillas" },
      { id: 62, name: "black beans", amount: 1, unit: "can", original: "1 can black beans" },
      { id: 65, name: "tomato", amount: 2, unit: "piece", original: "2 tomatoes" },
      { id: 63, name: "onion", amount: 1, unit: "piece", original: "1 onion" },
      { id: 69, name: "cilantro", amount: 1, unit: "bunch", original: "1 bunch cilantro" },
      { id: 68, name: "lemon", amount: 1, unit: "piece", original: "1 lemon" },
      { id: 67, name: "greek yogurt", amount: 100, unit: "g", original: "100g Greek yogurt" },
    ],
  },
];
